### ISSUE TITLE
Popraw dokumentacje

### ISSUE THREAD

**Issue by GrubySamuraj** [estwestminimu/if-you-know-you-know#1]
Dokumentacja jest co najmniej średnia - nie da się zrozumieć o co chodzi w danym teście, było, zamykam wątek. Chociażby do chata wrzuć

**Comment by estwestminimu** [comment]
"Github nie służy do nauki czytania  dokumentacji. **Szczególnie** podstaw.
Książki do ręki i do dzieła. Ewentualnie jakieś wykłady z projektowania (Wstęp na wykłady jest darmowy).
Zamykam"

**Comment by GrubySamuraj** [comment]
Niestety chyba autora boli to, że kod bez dokumentacji to tak samo jak Analiza bez Burka, bez sensu

**Comment by estwestminimu** [comment]
![OIP (8).jpeg](https://github.com/user-attachments/assets/d270da13-3f08-419e-aa91-2648b6c1befc)

**Comment by GrubySamuraj** [comment]
![image](https://github.com/user-attachments/assets/5a339279-2350-48a5-b1b3-4998275c879b)
